### ISSUE TITLE
Mantenimento codice dopo logout

### ISSUE THREAD

**Issue by PorfirioTramontana** [LZannini/Thesis#1]
In caso di logout il codice realizzato viene perduto (cosa che non avviene al cambio di pagina oppure alla chiusura e riapertura del browser).

Bisogna estendere il comportamento di salvataggio della sessione anche in caso di logout

**Comment by LZannini** [comment]
Ho risolto l'issue implementando la seguente logica:

Il localStorage non viene svuotato quando si effettua il logout, mentre nella fase di login, se l'utente che si logga ha una email diversa dall'email presente nel localStorage (quindi si logga un utente diverso da quello precedente), il localStorage viene svuotato.

Con questa implementazione però, se un unico utente usa l'applicazione, lo storage si accumula con i codici degli esercizi di refactor e degli esperimenti. Per questo motivo ho aggiunto nella pagina delle impostazioni una funzionalità che permette di svuotare il localStorage, nel caso in cui l'utente non abbia più bisogno delle informazioni accumulate, andando a liberare memoria occupata inutilmente.

**Comment by PorfirioTramontana** [comment]
Ok: quindi lo scenario del computer che si spegne improvvisamente o perde la connessione ora è coperto senza perdita di molti dati.

Lo scenario invece di un utente che interrompe un esercizio da un dispositivo (ad esempio in classe) e lo continua tempo dopo su di un altro dispositivo invece non è coperto (ma è uno scenario meno grave poichè alla chiusura volontaria della sessione l'utente potrebbe salvarsi una copia del suo lavoro.

P.S. C'è stata un'interruzione di corrente qui all'università esattamente mentre scrivevo questo messaggio.

**Comment by LZannini** [comment]
Si, giusto. Con questa nuova implementazione gli scenari più comuni sono coperti.
