### ISSUE TITLE
Missioni e livelli

### ISSUE THREAD

**Issue by PorfirioTramontana** [LZannini/Thesis#10]
Al profilo del giocatore va abbinato un livello di esperienza.

Ad ogni esercizio del refactoring game va abbinato un livello minimo di esperienza nel file nomeClasseConfig.json in ExerciseService.

Nella selezione degli esercizi il giocatore vede attivabili soltanto gli esercizi con livello di esperienza pari o inferiore al suo: gli altri li vede ma non sono selezionabili.

Problema del riconoscimento del superamento di un esercizio:
- soluzione 1 (manuale): il docente può scrivere sul file di informazioni di profilo di un utente e cambiare il suo livello. Scomodo perchè non abbiamo un'interfaccia docente
- soluzione 2 (automatica): ogni esercizio ha un un suo numero massimo di smell allowed e una sua massima perdita di coverage consentita (verificare che queste informazioni non siano globali ma dipendano dagli esercizi). Ad ogni Compilazione o Finish il sistema vede se i vincoli sono rispettati (smell risolti senza perdere molta coverage) e nel caso assegna il punto di esperienza.

Come abbellimento potremmo:
- ad ogni livello abbinare un'icona di reward da mostrare in un alert a video appena si raggiunge il livello.
- nella schermata principale possiamo far comparire il nome utente e i premi vinti / livelli di esperienza.

Situazione analoga per i quiz:
- c'è un valore minimo di esperienza nello stesso file json
- vengono visualizzati l'elenco dei quiz filtrati in base all'esperienza
- quando si supera il quiz si guadagna un livello
- il quiz si supera rispondendo correttamente a tutte le domande

**Comment by LZannini** [comment]
Ogni utente ha un proprio livello di esperienza (exp), che parte da 0 ed aumenta di 1 ad ogni esercizio completato. L'esperienza dell'utente corrisponde al numero di esercizi svolti. Il livello dell'utente è calcolato in questo modo:

- se 0 <= exp < 5, l'utente sarà di livello 1;
- se 5 <= exp < 15, l'utente sarà di livello 2;
- se exp >= 15 l'utente sarà di livello 3.

Quando l'utente, superando un esercizio, raggiungerà exp pari a 5 o 15, riceverà un messaggio dal sistema per il raggiungimento del nuovo livello.

Ho aggiunto una route profilo in cui ogni utente potrà visualizzare le proprie informazioni e stats. La pagina sarà accessibile dalla topbar, cliccando l'icona user in alto a destra.

Aggiunta di badges: l'utente al completamento di un determinato numero di esercizi riceverà i seguenti badges:

- badge bronzo: al completamento di 10 esercizi;
- badge argento: al completamento di 20 esercizi;
- badge oro: al completamento di 30 esercizi.

Quando l'utente completerà 10, 20 e 30 esercizi, dunque, riceverà un messaggio dal sistema per l'ottenimento dei badges, che potranno essere visualizzati all'interno della schermata profilo.

Ho abbinato un livello di difficoltà, da 1 a 3, ad ogni esercizio.

Nella modalità refactoring game l'esercizio sarà completato (ed il livello di esperienza incrementato) quando lo si aggiunge al Solution Repository, a patto che il numero di smell rimasti sia minore o uguale a quello degli smell permessi.

Nella modalità check smell game se l'utente risponderà correttamente a entrambe le domande allorà gli sarà attribuito un punto di esperienza. 

In entrambe le modalità di gioco l'utente potrà accedere solo agli esercizi il cui livello è minore o uguale al suo.

**Comment by PorfirioTramontana** [comment]
In generale va bene. 
Sarebbe importante che tutti i valori riportati (0, 5, 15 exp; 10, 20, 30 esercizi) non siano cablati nel codice ma siano modificabili e personalizzabili (è sufficiente che lo siano a livello globale, non a livello di giocatore o esperimento).

Anche il numero di risposte esatte al check smell game potrebbe essere personalizzabile anzichè cablato (ovviamente i quiz reali potranno avere ben più di 2 domande, per cui avrebb più senso poter fissare una percentuale di domande superate, ad esempio 90%).

**Comment by LZannini** [comment]
EDIT:

All'interno della directory 'src\assets\assets' del frontend è presente un file json 'level_config.json' che rende personalizzabili i valori di esperienza per i quali si ha un incremento del livello del giocatore o l'ottenimento di un badge. In più c'è un valore che rappresenta la percentuale di domande corrette per far si che un quiz sia considerato completato con successo. La struttura del file è la seguente:

{
  "expValues": [5, 15],
  "badgeValues": [10, 20, 30],
  "answerPercentage": 90
}

In questo modo è possibile personalizzare i seguenti valori all'interno del file stesso, senza modificare il codice del client.

**Comment by PorfirioTramontana** [comment]
Tutto bene, con alcune possibili migliorie:

- la configurazione dei livelli che ora si trova in src/assets/asssets può essere spostata verso il volume condiviso
- anche i badge (icons) possono essere spostate verso il volume condiviso
- per i badge anzichè solo i valori di punteggio necessari per ottenerli, si possono scrivere delle coppie [valore, file_icona] dove file_icona ovviamente punta al file nel volume condiviso. In questo modo è possibile modificare in qualsiasi momento sia il numero dei badge che le loro immagini che il numero di punti necessari per ottenerli
- tutti gli eventi rilevanti durate il gioco e/o durante gli assignments (esercizio completato, badge ottenuto, stella guadagnata, etc.) possono lasciare una traccia come riga in un file di log da tenere nel volume condiviso. Ad esempio una riga del log potrebbe essere:
data,ora login_giocatore descrizione evento

Per una migliore internazionalizzazione, cerca di mettere in inglese anche i nomi dei campi nei vari json (ad esempio 'nome', 'data', 'studenti', 'esercizio), mentre invece i nomi dei file li hai scritti già un pò tutti in inglese.

**Comment by LZannini** [comment]
- Configurazione dei livelli e file dei badge spostati sul volume in /assignments/levelconfig;

- badgeValues adesso contiene per ogni badge la coppia (int, string) dove il primo elemento è la soglia per arrivare al badge ed il secondo è il nome del file;

- nomi dei campi nel file json di un esperimento cambiati in inglese;

- aggiunta del file events.log (che verrà creato e inserito nel volume al primo evento e poi sovrascritto) nella directory /assignments/ del volume. Vengono loggati tutti gli eventi che riguardano il completamento di un esercizio (check game, refactoring game o assignment) o il raggiungimento di un nuovo livello o badge.
